// download: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@pathURL = http://localhost:3001
@childAddress = 0x554DAc4f6d076290dBa8469E9F2d1090A6DEd458
// childAddressToken6: 0x5e461b51f270947340b71b5d3a9fcB0C47EEb15b
// childAddressToken7: 0x554DAc4f6d076290dBa8469E9F2d1090A6DEd458
@rootAddress = 0x5E891015ED99d7C5c9eB5527658B4649F3f26c45
// rootAddressToken6: 0x1361d78d3375Eb11E0cc5a8a3423E3aC7c2513A5
// rootAddressToken7: 0x5E891015ED99d7C5c9eB5527658B4649F3f26c45
@owner = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA
@from = 0x91dDd8332bB2c94661D2192b15B93e27f0fEcEBA
@to = 0x43e6B95803ac909f31C46517691cd2e33e298e40

// POSContracts:
@predicate = 0x74D83801586E9D3C4dc45FfCD30B54eA9C88cf9b
// ERC721PredicateProxy: 0x74D83801586E9D3C4dc45FfCD30B54eA9C88cf9b
// MintableERC721PredicateProxy: 0x56E14C4C1748a818a5564D33cF774c59EB3eDF59
@operator = 0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74
// RootChainManager: 0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74 // RootChainManagerProxy

###
POST {{pathURL}}/api/child/details HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}"
}
###
POST {{pathURL}}/api/child/balance HTTP/1.1
content-type: application/json

{
  "owner": "{{owner}}",
  "nftAddress": "{{childAddress}}"
}
###
POST {{pathURL}}/api/child/tokenURI HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
###
POST {{pathURL}}/api/child/tokenByIndex HTTP/1.1
content-type: application/json

{
  "owner": "{{owner}}",
  "nftAddress": "{{childAddress}}",
  "index": 1
}
###
POST {{pathURL}}/api/child/totalSupply HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}"
}
###
POST {{pathURL}}/api/child/isApprovalAll HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "owner": "{{owner}}",
  "operator": "{{operator}}"
}
###
POST {{pathURL}}/api/child/approved HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
###
POST {{pathURL}}/api/child/encodeMetadata HTTP/1.1
content-type: application/json

{
  "nftAddress": "{{childAddress}}",
  "tokenId": 1
}
